# Generated by Django 5.2.4 on 2025-07-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_authorization_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
